
package com.gzsolartech.bpmportal.util.email;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendMail", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.128.97.145:8891/sendmail.asmx?wsdl")
public class SendMail
    extends Service
{

    private final static URL SENDMAIL_WSDL_LOCATION;
    private final static WebServiceException SENDMAIL_EXCEPTION;
    private final static QName SENDMAIL_QNAME = new QName("http://tempuri.org/", "SendMail");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.128.97.145:8891/sendmail.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDMAIL_WSDL_LOCATION = url;
        SENDMAIL_EXCEPTION = e;
    }

    public SendMail() {
        super(__getWsdlLocation(), SENDMAIL_QNAME);
    }

    public SendMail(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDMAIL_QNAME, features);
    }

    public SendMail(URL wsdlLocation) {
        super(wsdlLocation, SENDMAIL_QNAME);
    }

    public SendMail(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDMAIL_QNAME, features);
    }

    public SendMail(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMail(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendMailSoap
     */
    @WebEndpoint(name = "SendMailSoap")
    public SendMailSoap getSendMailSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SendMailSoap"), SendMailSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMailSoap
     */
    @WebEndpoint(name = "SendMailSoap")
    public SendMailSoap getSendMailSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SendMailSoap"), SendMailSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDMAIL_EXCEPTION!= null) {
            throw SENDMAIL_EXCEPTION;
        }
        return SENDMAIL_WSDL_LOCATION;
    }

}
